#ifndef IP_ITER_HPP
#define IP_ITER_HPP

#define MAT_A_CAP_NUM_ROWS	(NUM_EQUALITY_CONSTRAINTS + NUM_INEQUALITY_CONSTRAINTS)
#define MAT_A_CAP_NUM_COLS	(NUM_OPTMIZATION_VARIABLES + NUM_INEQUALITY_CONSTRAINTS)

#define LAGRANGE_MULTIPLIERS_SIZE  (NUM_EQUALITY_CONSTRAINTS + NUM_INEQUALITY_CONSTRAINTS)

#endif // IP_ITER_HPP

